### ISSUE TITLE
Error on Blogger import

### ISSUE THREAD

**Issue by mnyon-grandkru** [mnyon-grandkru/mnyon.com#1]
```
/usr/share/rvm/gems/ruby-3.2.2@mnyon.com/gems/jekyll-import-0.22.0/lib/jekyll-import/importers/blogger.rb:258:in `post_data_from_in_entry_elem_info': Original URL is missing (RuntimeError)
        from /usr/share/rvm/gems/ruby-3.2.2@mnyon.com/gems/jekyll-import-0.22.0/lib/jekyll-import/importers/blogger.rb:190:in `tag_end'
        from /usr/share/rvm/gems/ruby-3.2.2@mnyon.com/gems/rexml-3.2.6/lib/rexml/parsers/streamparser.rb:36:in `parse'
        from /usr/share/rvm/gems/ruby-3.2.2@mnyon.com/gems/jekyll-import-0.22.0/lib/jekyll-import/importers/blogger.rb:47:in `block in process'
        from /usr/share/rvm/gems/ruby-3.2.2@mnyon.com/gems/jekyll-import-0.22.0/lib/jekyll-import/importers/blogger.rb:45:in `open'
        from /usr/share/rvm/gems/ruby-3.2.2@mnyon.com/gems/jekyll-import-0.22.0/lib/jekyll-import/importers/blogger.rb:45:in `process'
        from /usr/share/rvm/gems/ruby-3.2.2@mnyon.com/gems/jekyll-import-0.22.0/lib/jekyll-import/importer.rb:25:in `run'
        from /usr/share/rvm/gems/ruby-3.2.2@mnyon.com/gems/jekyll-import-0.22.0/lib/jekyll-import.rb:30:in `block (3 levels) in add_importer_commands'
        from /usr/share/rvm/gems/ruby-3.2.2@mnyon.com/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /usr/share/rvm/gems/ruby-3.2.2@mnyon.com/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /usr/share/rvm/gems/ruby-3.2.2@mnyon.com/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /usr/share/rvm/gems/ruby-3.2.2@mnyon.com/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /usr/share/rvm/gems/ruby-3.2.2@mnyon.com/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /usr/share/rvm/gems/ruby-3.2.2@mnyon.com/gems/jekyll-4.3.2/exe/jekyll:15:in `<top (required)>'
        from /usr/share/rvm/gems/ruby-3.2.2@mnyon.com/bin/jekyll:25:in `load'
        from /usr/share/rvm/gems/ruby-3.2.2@mnyon.com/bin/jekyll:25:in `<main>'
        from /usr/share/rvm/gems/ruby-3.2.2@mnyon.com/bin/ruby_executable_hooks:22:in `eval'
        from /usr/share/rvm/gems/ruby-3.2.2@mnyon.com/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by mnyon-grandkru** [comment]
Needed to add jekyll-import
